### ISSUE TITLE
Development API

### ISSUE THREAD

**Issue by billdybas** [rit-sse/node-api#33]
It would be advantageous to set up a **development API** for the SSE so we **don't have to run our own** every time we want to make a change to any SSE repo that uses the API. Setting up a dev API will also **lower the barrier of entry** for working on and maintaining SSE repos, and as a result potentially increasing participation and collaboration.

**Comment by kristenmills** [comment]
My thoughts on this:
1. Running the API locally is not a big deal. Once you do the one time setup of the keys, it's trivial
2. While developing you are going to want to be able to have your user be a primary officer. So now instead of just running the bootstrap script, you now have to find some who is already an officer to give you admin access and the time you spent doing that, you could have just set up the API on your local machine.

**Comment by 7imbrook** [comment]
We will be setting up a dev environment as well, it will have more admins and will reset at midnight everyday. So no harm in testing against it. However the best way is going to be to pull the docker image and run that locally and that's what we'll encourage. This is easier than setting up the api, but not by much. Dev is going to be more of a integration/verification environment anyway.

**Comment by vuzDylan** [comment]
This is also fixed in the new version of the site which default points at prod
